# Generated by Django 2.0.5 on 2018-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeCase',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('Longitude', models.FloatField()),
                ('Latitede', models.FloatField()),
                ('Deep', models.IntegerField()),
                ('Address', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='earthquakecase',
            unique_together={('Longitude', 'Latitede', 'Time')},
        ),
    ]
